name: PublishToNpm
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Is Publish Available
        run : npx can-npm-publish --verbose
      - name: Install
        run : npm install
      - name: Test
        run : npm test
      - name: Build
        run : npm run build --if-present
      - name: Publish
        run : npm publish --access=public
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}